### ISSUE TITLE
Inplace operations

### ISSUE THREAD

**Issue by mcaresein** [francescogrienti/PyTorchLearning#1]
https://github.com/francescogrienti/PyTorchLearning/blob/a7948a9494905659126d9cb22961c6fb3abeb609/Exercise1/polinomial_fit.py#L36

Ciao, proviamo un'interazione via github issues e vediamo come va!
Noto che usi le operazioni inplace di torch.nn.functional, ma poi le assegni comunque ad x. Non mi e' chiaro che comportamento abbia questo. Tra l'altro, leggendo [qua](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#tensor-operations) dice che le inplace interferiscono con la backpropagation. 

Poi, tu hai capito la differenza tra torch.nn.functional.selu e torch.nn.SELU?

Altra cosa: dal tutorial di pytorch mi sembra di capire che anche le nonlinearità siano messe come datamembri. Tu così non lo stai facendo. Ci sono pro e contro?

**Comment by francescogrienti** [comment]
Ciao Michele, 
per quanto riguarda il primo punto si tratta di una scrittura ridondante: essendo le operazioni in-place non è necessario riassegnarle alla variabile, tuttavia quando faccio operazioni simili legate alla memoria tendo a non fidarmi e ad essere ridondante. Anche perchè, come dici tu nella seconda parte, sembra da documentazione poter essere pericolosa nella backpropagation. 

Per il secondo punto, la differenza pare essere legata alla struttura: torch.nn.SELU è una classe (che eredita da nn.Module) a sè stante in cui è implementata la non linearità esattamente come in torch.nn.functional. Quest'ultima invece pare essere una semplice funzione che prende in ingresso l'input e restituisce l'output. La differenza nell'utilizzo si ricollega all'ultimo punto che hai sollevato: usare torch.nn.SELU significa definire un layer nella NN usando l'approccio OO, quindi definendo il layer come data membro nel costruttore della classe. Il vantaggio sta nel fatto che il codice risulta così più leggibile e manutenibile, tuttavia qualche problema può sorgere nel momento in cui ho, ad esempio, parecchi layer tutti con diverse nonlinearità....in questo caso significherebbe instanziare diverse classi (nn.SELU, nn.RELU, ecc ) e questo renderebbe il codice piuttosto complesso. 
L'utilizzo di torch.nn.functional potrebbe tornare utile per situazioni in l'utilizzo di una particolare nonlinearità è legato ad una certa condizione da soddisfare: in questo caso ha ovviamente poco senso instanziare un layer con una definita nonlinearità, mentre ha più senso definire un if nel forward method e richiamare le funzioni nonlineari di interesse. 

Grazie dei punti che hai sollevato, è stato utile anche a me per capire meglio alcune cose :) ! Se sono stato poco chiaro fammi sapere.

**Comment by mcaresein** [comment]
Mi spiace ma ti farò un po' le pulci perche' ho bisogno di imparare pure io bene ste cose ahahah

> per quanto riguarda il primo punto si tratta di una scrittura ridondante: essendo le operazioni in-place non è necessario riassegnarle alla variabile, tuttavia quando faccio operazioni simili legate alla memoria tendo a non fidarmi e ad essere ridondante. Anche perchè, come dici tu nella seconda parte, sembra da documentazione poter essere pericolosa nella backpropagation.

Ok però allora perchè usare l'istruzione in place se poi la assegni? E' comunque più rapido? 

>  La differenza nell'utilizzo si ricollega all'ultimo punto che hai sollevato: usare torch.nn.SELU significa definire un layer nella NN usando l'approccio OO, quindi definendo il layer come data membro nel costruttore della classe. Il vantaggio sta nel fatto che il codice risulta così più leggibile e manutenibile, tuttavia qualche problema può sorgere nel momento in cui ho, ad esempio, parecchi layer tutti con diverse nonlinearità....in questo caso significherebbe instanziare diverse classi (nn.SELU, nn.RELU, ecc ) e questo renderebbe il codice piuttosto complesso.

beh in realtà penso tu debba farlo comunque anche se usi la stessa nonlinearità tra diversi layer. Cioe' mi immagino una cosa tipo 
   
     self.layer1 = nn.linear(in_dim, out_dim)
     self.gelu1 = nn.GELU()
     self.layer2 = nn.linear(in_dim, out_dim)
     self.gelu2 = nn.GELU()

nel costruttore e una cosa tipo

    x = self.gelu1(self.layer1(x))
    x = self.gelu2(self.layer1(x))

e la stessa cosa se usassi F.gelu(), altrimenti mi aspetto un loop nel grafo della backpropagation no?

**Comment by francescogrienti** [comment]
Ciao Michele, 

per quanto riguarda la seconda osservazione credo tu abbia ragione. Nella logica dell'OO, avrebbe senso instanziare diversi oggetti della stessa classe, anche perché sono oggetti stateful e quindi "assegnandoli" a layer diversi cambiano i dati che si stanno trattando (spiegato un po' male ma spero si sia compreso). La stessa cosa vale in maniera diversa per F.gelu(), ma solo per il fatto che è una semplice chiamata di funzione (questo dovrebbe essere un oggetto di tipo stateless). 

Per quanto riguarda il primo punto, non riesco a capire se tu ti stia ponendo quella domanda con qualche fine: se mi stai chiedendo "indaga sul senso di utilizzare una in-place operation e poi utilizzare l'assegnazione" mi ci metto sotto, ma da quanto ho letto le operazioni in-place hanno diversi vantaggi in termini di efficienza di memoria e performance migliori. La riassegnazione alla variabile potrebbe, a mio modesto modo di vedere, rallentare invece il tempo computazionale perché in sostanza viene ripetuta una seconda volta una operazione che è già implicita nell'in-place. Per queste ragioni mi verrebbe da dirti che per ora, visti anche i potenziali problemi che possono sorgere nella backpropagation, tenderei a metterla in panchina e tirarla fuori nel momento in cui può tornare utile per efficientare il codice, ma nel caso fammi sapere e ne parliamo. Ah, buon viaggio in Giappone intanto! 

In questi giorni risolverò l'altro notebook dove ci sono le CNN. Volevo poi girarti il link di un corso di PyTorch di FreeCodeCamp (molto lungo, ma facendolo spezzettato si può fare :) https://www.youtube.com/watch?v=V_xro1bcAuA&t=6198s, fammi sapere che ne pensi!

**Comment by mcaresein** [comment]
> per quanto riguarda la seconda osservazione credo che basti instanziare una sola volta l'oggetto e utilizzarlo il numero di volte che si desidera. Da quanto ho letto in giro, le classi activation functions sono oggetti stateless, dunque loro non memorizzano nessun parametro utile durante l'allenamento...applicano semplicemente una trasformazione non lineare a dei dati di input. Lo stesso discorso di oggetto stateless vale per torch.nn.functional...qui semplicemente chiamo la funzione il numero di volte a me necessario e viene applicata una trasformazione non lineare.

Chiarissimo! probabilmente a sto punto le nn.activation chiameranno al proprio interno le nn.functional.activation immagino... comunque sticazzi una vale l'altra direi. 

> Per quanto riguarda il primo punto, non riesco a capire se tu ti stia ponendo quella domanda con qualche fine: se mi stai chiedendo "indaga sul senso di utilizzare una in-place operation e poi utilizzare l'assegnazione" mi ci metto sotto, ma da quanto ho letto le operazioni in-place hanno diversi vantaggi in termini di efficienza di memoria e performance migliori. La riassegnazione alla variabile potrebbe, a mio modesto modo di vedere, rallentare invece il tempo computazionale perché in sostanza viene ripetuta una seconda volta una operazione che è già implicita nell'in-place. Per queste ragioni mi verrebbe da dirti che per ora, visti anche i potenziali problemi che possono sorgere nella backpropagation, tenderei a metterla in panchina e tirarla fuori nel momento in cui può tornare utile per efficientare il codice, ma nel caso fammi sapere e ne parliamo. Ah, buon viaggio in Giappone intanto!

Anche secondo me ad intuito rallenta, per questo volevo sapere anche il tuo punto di vista. Direi in ogni caso di lasciar perdere le inplace principalmente per i problemi di backpropagation. Anche perche' i vantaggi dovrebbero essere solo a livello di uso di memoria, e non di tempo computazionale. Poi bisognerebbe anche indagare se i vantaggi si mantengono anche con le gpu oppure cosa succede li. 

> In questi giorni risolverò l'altro notebook dove ci sono le CNN. Volevo poi girarti il link di un corso di PyTorch di FreeCodeCamp (molto lungo, ma facendolo spezzettato si può fare :) https://www.youtube.com/watch?v=V_xro1bcAuA&t=6198s, fammi sapere che ne pensi!

mooooolto lungo ahhaha ma interessante! ottima referenza
